---
title: "R Bridge Week 1 Assignment"
author: "Donald Butler"
date: "7/20/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise #1. 

Write a loop that calculates 12-factorial.

```{r factorial}
result <- 1
for (i in 12:1){
  result <- result * i
}
result
```

## Exercise #2.

Show how to create a numeric vector that contains the sequence from 20 to 50 by 5.

```{r vector}
v <- (4:10)*5
v
```

## Exercise #3.

Create the function "quadratic" that takes a trio of input numbers a, b, and c and solve the quadratic equation. The function should print as output the two solutions.

```{r quardratic}
quadratic <- function(a,b,c){
  if (b^2 < 4*a*c){
    result <- "No real roots"
  }else{
    result <- c((-b + sqrt(b^2 - 4 * a * c))/(2 * a),(-b - sqrt(b^2 - 4 * a * c))/(2 * a))
  }
  return (result)
}

quadratic(a = 1, b = 2, c = 1)
quadratic(a = 1, b = 0, c = 25)
quadratic(a = 3, b = 3, c = -6)

```

